name: Playwright Tests with Allure Report

on:
  push:
    branches: [ main,master,local ]
  pull_request:
    branches: [ main,master,local ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # needed to push Allure report to gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages

